version: '3.8'

services:
  basededatos:
    image: mongo:latest
    container_name: mi_mongo_local
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: pdf_extractor_app
    depends_on:
      - basededatos
    volumes:
      - .:/app
    command: python main.py pdfs/mi_documento.pdf 

volumes:
  mongo_data: